-- 053_company_round_type_taxonomy.sql — seed company_interview_profiles with the
-- technical round_type for 48 high-frequency target companies (+2 name aliases).
--
-- Purpose: lets the Technical workspace + coach calibrate DSA emphasis per company.
--   Each row carries a single `technical-1` process_shape entry whose `round_type`
--   the admin-api + coach resolvers read (first stage starting with 'technical').
--   round_type taxonomy: dsa | practical | take-home | system-design | mixed.
--
-- Provenance: every row's `source` cites a 2024-2026 interview report (Glassdoor,
--   interviewing.io, eng blogs, InterviewQuery, Exponent, TechPrep, Taro, IGotAnOffer,
--   prepfully, vendor handbooks). Confidence (high|medium|low) is recorded both in the
--   row `source` text and in each process_shape entry's `confidence` field — honest:
--   low-confidence rows are inferred, not asserted. Retrieved 2026-06-02.
--
-- Honesty notes:
--   * microsoft: no reliable 2024+ source found in research — seeded 'dsa' (the long-
--     standing default) at confidence 'low', flagged inferred. Safe-mode default is 'dsa'
--     anyway, so a wrong guess here does not over-hide DSA.
--   * Amazon + Stripe are intentionally NOT touched here — migration 052 owns their
--     richer 3-stage process_shape. Re-running 053 will not clobber them.
--   * Aliases (square -> Block, mistralai -> Mistral) cover the two dual-name companies
--     so normalizeCompanyKey() hits regardless of which name a user typed.
--
-- Idempotent: INSERT ... ON CONFLICT (company_key) DO UPDATE — safe to re-run.
BEGIN;

INSERT INTO company_interview_profiles (company_key, display_name, company_type, process_shape, source, as_of) VALUES
('google','Google','faang','[{"stage":"technical-1","format":"2-3 algorithm coding rounds (shared editor)","note":"LeetCode medium-hard DSA; 2026 adds an AI-assisted code-comprehension round","round_type":"dsa","confidence":"high"}]'::jsonb,'Exponent Google SWE Guide 2026 (tryexponent.com/guides/google-swe-interview), retrieved 2026-06-02; confidence high','2026-06-02'),
('meta','Meta','faang','[{"stage":"technical-1","format":"45-min CoderPad coding rounds","note":"Two LeetCode med-hard per round; late-2025 added one AI-enabled coding round","round_type":"dsa","confidence":"high"}]'::jsonb,'IGotAnOffer Meta Coding Interviews 2025 (igotanoffer.com/en/advice/meta-coding-interviews), retrieved 2026-06-02; confidence high','2026-06-02'),
('apple','Apple','faang','[{"stage":"technical-1","format":"team-dependent technical loop","note":"Some teams LeetCode-medium DSA, others domain-practical + low-level/system design; no dominant format","round_type":"mixed","confidence":"medium"}]'::jsonb,'interviewing.io Apple Guide 2025 (interviewing.io/guides/hiring-process/apple), retrieved 2026-06-02; confidence medium','2026-06-02'),
('microsoft','Microsoft','bigtech','[{"stage":"technical-1","format":"coding rounds","note":"Standard LeetCode-style DSA; no reliable 2024+ source found - inferred from long-standing format","round_type":"dsa","confidence":"low"}]'::jsonb,'No reliable 2024+ source found; inferred. Retrieved 2026-06-02; confidence low','2026-06-02'),
('netflix','Netflix','bigtech','[{"stage":"technical-1","format":"CoderPad/CodeSignal coding screen","note":"Production-style problems (rate limiter, cache) over puzzles; system design weighs most","round_type":"practical","confidence":"medium"}]'::jsonb,'interviewing.io Netflix Guide 2025 (interviewing.io/guides/hiring-process/netflix), retrieved 2026-06-02; confidence medium','2026-06-02'),
('nvidia','Nvidia','bigtech','[{"stage":"technical-1","format":"2-3 one-hour coding rounds (CoderPad)","note":"LeetCode-medium algorithms, often C++; some teams use low-level/debug variants","round_type":"dsa","confidence":"high"}]'::jsonb,'IGotAnOffer NVIDIA SWE 2025 (igotanoffer.com/en/advice/nvidia-software-engineer-interview), retrieved 2026-06-02; confidence high','2026-06-02'),
('openai','OpenAI','ai','[{"stage":"technical-1","format":"60-min progressive coding + 48h work-trial","note":"State/concurrency gate problem + build a real system (webhook delivery); graded on reliability/tests, not algorithms","round_type":"practical","confidence":"high"}]'::jsonb,'Hello Interview OpenAI Coding 2025 (hellointerview.com/blog/openai-coding-questions), retrieved 2026-06-02; confidence high','2026-06-02'),
('anthropic','Anthropic','ai','[{"stage":"technical-1","format":"~90-min CodeSignal build","note":"Python: build a working system across 4 progressive levels vs a test harness; explicitly not LeetCode","round_type":"practical","confidence":"high"}]'::jsonb,'interviewing.io Anthropic Interview Questions 2025 (interviewing.io/anthropic-interview-questions), retrieved 2026-06-02; confidence high','2026-06-02'),
('spotify','Spotify','bigtech','[{"stage":"technical-1","format":"level/team-dependent","note":"OA, take-home API, live CoderPad, or code-review/bug-find depending on level; no dominant type","round_type":"mixed","confidence":"medium"}]'::jsonb,'TechPrep Spotify Process 2026 (techprep.app/blog/spotify-interview-process), retrieved 2026-06-02; confidence medium','2026-06-02'),
('revolut','Revolut','fintech','[{"stage":"technical-1","format":"live IDE build (45-60m)","note":"Build a small service (load balancer, transfer w/ concurrency); preceded by HackerRank DS&A/SQL screen","round_type":"practical","confidence":"high"}]'::jsonb,'InterviewQuery Revolut SWE 2025 (interviewquery.com/interview-guides/revolut-software-engineer), retrieved 2026-06-02; confidence high','2026-06-02'),
('wise','Wise','fintech','[{"stage":"technical-1","format":"paired coding + system design","note":"Real production patterns (circuit breaker); some platform roles get a take-home","round_type":"practical","confidence":"medium"}]'::jsonb,'Wise Jobs / Glassdoor 2025 (wise.jobs/step-2-interview), retrieved 2026-06-02; confidence medium','2026-06-02'),
('adyen','Adyen','fintech','[{"stage":"technical-1","format":"screen + live + deep-dive","note":"HackerRank/take-home (DS&A+SQL) then live coding then deep-dive; no dominant type","round_type":"mixed","confidence":"medium"}]'::jsonb,'InterviewQuery Adyen SWE 2025 (interviewquery.com/interview-guides/adyen-software-engineer), retrieved 2026-06-02; confidence medium','2026-06-02'),
('monzo','Monzo','fintech','[{"stage":"technical-1","format":"take-home + review call","note":"Choose a take-home (web crawler) + 45-min review of trade-offs/fault handling; pairing alt","round_type":"take-home","confidence":"high"}]'::jsonb,'Monzo Engineering Blog 2025 (monzo.com/blog/demystifying-the-backend-engineering-interview-process), retrieved 2026-06-02; confidence high','2026-06-02'),
('klarna','Klarna','fintech','[{"stage":"technical-1","format":"OA + live coding","note":"Algorithmic challenge then live shared-editor algo problems; system design for senior","round_type":"dsa","confidence":"medium"}]'::jsonb,'InterviewQuery Klarna SWE 2025 (interviewquery.com/interview-guides/klarna-software-engineer), retrieved 2026-06-02; confidence medium','2026-06-02'),
('n26','N26','fintech','[{"stage":"technical-1","format":"Codility assessment + live","note":"3 problems (2 med + 1 hard) then live programming + system design","round_type":"dsa","confidence":"medium"}]'::jsonb,'Medium N26 Berlin SWE Experience Jan 2026 (freezefrancis.medium.com/n26-berlin-software-engineer-interview-experience-88ee71c3f89c), retrieved 2026-06-02; confidence medium','2026-06-02'),
('checkoutcom','Checkout.com','fintech','[{"stage":"technical-1","format":"pair-programming on real API","note":"Implement an endpoint in an existing ASP.NET API + take-home + testing discussion","round_type":"practical","confidence":"medium"}]'::jsonb,'Taro / Glassdoor 2025 (jointaro.com/interviews/companies/checkoutcom), retrieved 2026-06-02; confidence medium','2026-06-02'),
('block','Block (Square)','fintech','[{"stage":"technical-1","format":"pair-programming real-world","note":"Data-processing problem (transaction-stream detection), readable code; LLD in Java/Go","round_type":"practical","confidence":"high"}]'::jsonb,'TechPrep Block Process 2025 (techprep.app/blog/block-interview-process), retrieved 2026-06-02; confidence high','2026-06-02'),
('coinbase','Coinbase','fintech','[{"stage":"technical-1","format":"Tech Execution pairing","note":"Build a real system (order management/trade-matching), production-grade runnable code over LeetCode-optimal","round_type":"practical","confidence":"high"}]'::jsonb,'Coinbase Engineering Blog 2025 (coinbase.com/blog/how-coinbase-interviews-for-engineering-roles), retrieved 2026-06-02; confidence high','2026-06-02'),
('datadog','Datadog','devtools','[{"stage":"technical-1","format":"CoderPad pairing + design","note":"Practical + medium DSA blend plus distributed-systems design; no dominant type","round_type":"mixed","confidence":"high"}]'::jsonb,'TechPrep Datadog Process 2026 (techprep.app/blog/datadog-interview-process), retrieved 2026-06-02; confidence high','2026-06-02'),
('hashicorp','HashiCorp','devtools','[{"stage":"technical-1","format":"machine-coding + PR review","note":"Realistic task (often Go) + a PR review; no LeetCode","round_type":"practical","confidence":"high"}]'::jsonb,'InterviewQuery HashiCorp SWE 2025 (interviewquery.com/interview-guides/hashicorp-software-engineer), retrieved 2026-06-02; confidence high','2026-06-02'),
('gitlab','GitLab','devtools','[{"stage":"technical-1","format":"MR review + live coding","note":"Review a real merge request sent 72h ahead + a live coding exercise; work-sample not DSA","round_type":"practical","confidence":"high"}]'::jsonb,'GitLab Handbook 2025 (handbook.gitlab.com/handbook/hiring/interviewing/technical/), retrieved 2026-06-02; confidence high','2026-06-02'),
('github','GitHub','devtools','[{"stage":"technical-1","format":"async take-home + review","note":"Build a small API (~3-5h) submitted as an anonymized PR w/ tests + a code-review discussion","round_type":"take-home","confidence":"high"}]'::jsonb,'GitHub Blog 2025 (github.blog/developer-skills/career-growth/how-github-does-take-home-technical-interviews/), retrieved 2026-06-02; confidence high','2026-06-02'),
('cloudflare','Cloudflare','devtools','[{"stage":"technical-1","format":"CoderPad real-product coding + Code Pair","note":"Rate limiter / log aggregation problems; clean working code over puzzles","round_type":"practical","confidence":"high"}]'::jsonb,'TechPrep Cloudflare Process 2026 (techprep.app/blog/cloudflare-interview-process), retrieved 2026-06-02; confidence high','2026-06-02'),
('vercel','Vercel','devtools','[{"stage":"technical-1","format":"build/debug + code review","note":"Production-style app build/debug under constraints + a live code review","round_type":"practical","confidence":"medium"}]'::jsonb,'InterviewQuery Vercel SWE 2025 (interviewquery.com/prep-guides/vercel-software-engineer), retrieved 2026-06-02; confidence medium','2026-06-02'),
('mongodb','MongoDB','devtools','[{"stage":"technical-1","format":"LeetCode-style rounds","note":"K-Sum, Group Anagrams, Word Break, iterators + design/concurrency","round_type":"dsa","confidence":"high"}]'::jsonb,'InterviewQuery MongoDB SWE 2025 (interviewquery.com/interview-guides/mongodb-software-engineer), retrieved 2026-06-02; confidence high','2026-06-02'),
('confluent','Confluent','devtools','[{"stage":"technical-1","format":"HackerRank/CoderPad DSA","note":"Medium DSA extending into concurrency/LLD + distributed-systems design","round_type":"dsa","confidence":"high"}]'::jsonb,'TechPrep Confluent Process 2026 (techprep.app/blog/confluent-interview-process), retrieved 2026-06-02; confidence high','2026-06-02'),
('snowflake','Snowflake','devtools','[{"stage":"technical-1","format":"LeetCode coding (hard-skew)","note":"Graphs/DP/concurrency (thread-safe LRU) + infra system design + SQL","round_type":"dsa","confidence":"high"}]'::jsonb,'TechPrep Snowflake Process 2026 (techprep.app/blog/snowflake-interview-process), retrieved 2026-06-02; confidence high','2026-06-02'),
('databricks','Databricks','devtools','[{"stage":"technical-1","format":"CodeSignal/CoderPad med-hard","note":"Graphs, binary search, concurrency + distributed-data-systems design","round_type":"dsa","confidence":"high"}]'::jsonb,'InterviewQuery Databricks SWE 2025 (interviewquery.com/interview-guides/databricks-software-engineer), retrieved 2026-06-02; confidence high','2026-06-02'),
('atlassian','Atlassian','scaleup','[{"stage":"technical-1","format":"60-min Karat coding","note":"DSA fundamentals (DP, BFS, graphs), any language, clean code","round_type":"dsa","confidence":"high"}]'::jsonb,'interviewing.io Atlassian 2025 (interviewing.io/atlassian-interview-questions), retrieved 2026-06-02; confidence high','2026-06-02'),
('twilio','Twilio','scaleup','[{"stage":"technical-1","format":"HackerRank OA + live","note":"1-2 LeetCode easy/medium (arrays, hash, trees, BFS/DFS, graphs)","round_type":"dsa","confidence":"high"}]'::jsonb,'codinginterview.com Twilio 2025 (codinginterview.com/guide/twilio-interview/), retrieved 2026-06-02; confidence high','2026-06-02'),
('shopify','Shopify','scaleup','[{"stage":"technical-1","format":"CoderPad challenge + pairing","note":"Live pair-programming to build a feature/debug; real-world over LeetCode","round_type":"practical","confidence":"high"}]'::jsonb,'Shopify Engineering 2025 (shopify.engineering/nail-your-technical-shopify-interview), retrieved 2026-06-02; confidence high','2026-06-02'),
('uber','Uber','bigtech','[{"stage":"technical-1","format":"CodeSignal/CoderPad coding","note":"Runnable, edge-case-tested medium+ LeetCode DSA (~35 min)","round_type":"dsa","confidence":"high"}]'::jsonb,'Exponent Uber SWE 2026 (tryexponent.com/guides/uber-software-engineer-interview), retrieved 2026-06-02; confidence high','2026-06-02'),
('airbnb','Airbnb','bigtech','[{"stage":"technical-1","format":"CoderPad/HackerRank coding","note":"Real working code on med-hard DSA (arrays, trees, graphs, DFS/BFS, DP)","round_type":"dsa","confidence":"high"}]'::jsonb,'Exponent Airbnb SWE 2026 (tryexponent.com/guides/airbnb-software-engineer-interview), retrieved 2026-06-02; confidence high','2026-06-02'),
('notion','Notion','scaleup','[{"stage":"technical-1","format":"functional-requirement coding","note":"Build a feature w/ clean code + trade-offs (TS/React), often AI-tool-enabled","round_type":"practical","confidence":"medium"}]'::jsonb,'InterviewQuery Notion Labs SWE 2026 (interviewquery.com/interview-guides/notion-labs-software-engineer), retrieved 2026-06-02; confidence medium','2026-06-02'),
('figma','Figma','scaleup','[{"stage":"technical-1","format":"CoderPad rounds (2x60m)","note":"Google L4/L5 LeetCode-medium+ with an applied UI/state twist (LRU custom eviction)","round_type":"dsa","confidence":"high"}]'::jsonb,'techinterview.org Figma 2026 (techinterview.org/companies/figma/), retrieved 2026-06-02; confidence high','2026-06-02'),
('canva','Canva','scaleup','[{"stage":"technical-1","format":"2x60-min coding + pairing","note":"Core DSA: graphs, stacks, queues, hash maps, heaps, linked lists, recursion, sort","round_type":"dsa","confidence":"high"}]'::jsonb,'algo.monster Canva 2025 (algo.monster/interview-guides/canva), retrieved 2026-06-02; confidence high','2026-06-02'),
('palantir','Palantir','enterprise','[{"stage":"technical-1","format":"DSA screen + Decomposition","note":"Narrative DSA coding + signature Decomposition (data models/API/logic); no dominant type","round_type":"mixed","confidence":"high"}]'::jsonb,'TechPrep Palantir Process 2026 (techprep.app/blog/palantir-interview-process), retrieved 2026-06-02; confidence high','2026-06-02'),
('robinhood','Robinhood','fintech','[{"stage":"technical-1","format":"CodeSignal OA + Karat/CoderPad","note":"DSA mapped to finance (heaps, sliding window, graphs, DP) + concurrency/thread-safety bar","round_type":"dsa","confidence":"high"}]'::jsonb,'interviewing.io Robinhood 2026 (interviewing.io/robinhood-interview-questions), retrieved 2026-06-02; confidence high','2026-06-02'),
('mistral','Mistral AI','ai','[{"stage":"technical-1","format":"coding + LLM quiz + AI design","note":"Medium LeetCode (sometimes attention-from-scratch) + LLM-knowledge quiz + RAG system design; no dominant type","round_type":"mixed","confidence":"medium"}]'::jsonb,'InterviewQuery Mistral AI SWE 2026 (interviewquery.com/prep-guides/mistral-ai-software-engineer), retrieved 2026-06-02; confidence medium','2026-06-02'),
('huggingface','Hugging Face','ai','[{"stage":"technical-1","format":"untimed take-home + walkthrough","note":"Spaces demo/dataset card/bug fix/notebook then discussion; open-source style over algos","round_type":"take-home","confidence":"medium"}]'::jsonb,'Glassdoor Hugging Face 2026 (glassdoor.com/Interview/Hugging-Face-Interview-Questions-E6487302.htm), retrieved 2026-06-02; confidence medium','2026-06-02'),
('cohere','Cohere','ai','[{"stage":"technical-1","format":"take-home + practical rounds","note":"Take-home first (~30% pass) then practical job-specific Python, not LeetCode","round_type":"take-home","confidence":"medium"}]'::jsonb,'Taro Cohere SWE Oct 2025 (jointaro.com/interviews/companies/cohere), retrieved 2026-06-02; confidence medium','2026-06-02'),
('sap','SAP','enterprise','[{"stage":"technical-1","format":"OA + live coding","note":"~2 DSA (easy/med) + MCQs then ~60-min medium algorithm/OOP, code clarity matters","round_type":"dsa","confidence":"medium"}]'::jsonb,'InterviewQuery SAP SWE 2025 (interviewquery.com/interview-guides/sap-software-engineer), retrieved 2026-06-02; confidence medium','2026-06-02'),
('bookingcom','Booking.com','bigtech','[{"stage":"technical-1","format":"live coding in online IDE","note":"Practical business-framed problems (build cache, extend service), Java, with 2 engineers","round_type":"practical","confidence":"medium"}]'::jsonb,'InterviewQuery Booking.com SWE 2026 (interviewquery.com/interview-guides/bookingcom-software-engineer), retrieved 2026-06-02; confidence medium','2026-06-02'),
('getyourguide','GetYourGuide','scaleup','[{"stage":"technical-1","format":"HackerRank + live on real repo","note":"Refactor a real GitHub codebase, write tests, explain endpoints (Java/Spring) + system design","round_type":"practical","confidence":"medium"}]'::jsonb,'prepfully GetYourGuide Full Stack 2026 (prepfully.com/interview-questions/getyourguide/full-stack-software-engineer), retrieved 2026-06-02; confidence medium','2026-06-02'),
('celonis','Celonis','enterprise','[{"stage":"technical-1","format":"coding assessment (take-home/live)","note":"Mostly medium LeetCode DS&A (~4 easy/12 med/2 hard) + team/managerial rounds","round_type":"dsa","confidence":"medium"}]'::jsonb,'InterviewQuery Celonis SWE 2025 (interviewquery.com/interview-guides/celonis-software-engineer), retrieved 2026-06-02; confidence medium','2026-06-02'),
('personio','Personio','scaleup','[{"stage":"technical-1","format":"two algorithmic rounds","note":"LeetCode-medium under time + LeetCode-hard debugging/edge-cases (arrays/hash)","round_type":"dsa","confidence":"medium"}]'::jsonb,'prepfully Personio SWE 2026 (prepfully.com/interview-questions/personio/software-engineer), retrieved 2026-06-02; confidence medium','2026-06-02'),
('elastic','Elastic','devtools','[{"stage":"technical-1","format":"coding + design + product deep-dive","note":"Timed live-coding + system design + architecture discussion (TS/Node/React); no dominant type","round_type":"mixed","confidence":"low"}]'::jsonb,'Glassdoor Elastic SWE 2025 (glassdoor.com/Interview/Elastic-Software-Engineer-Interview-Questions-EI_IE751551.htm), retrieved 2026-06-02; confidence low','2026-06-02'),
('grafanalabs','Grafana Labs','devtools','[{"stage":"technical-1","format":"live coding + NALSD","note":"60-min collaborative coding + Non-Abstract Large System Design, sometimes a take-home","round_type":"mixed","confidence":"medium"}]'::jsonb,'Glassdoor Grafana Labs 2026 (glassdoor.com/Interview/Grafana-Labs-Interview-Questions-E2300269.htm), retrieved 2026-06-02; confidence medium','2026-06-02'),
('square','Square (Block)','fintech','[{"stage":"technical-1","format":"pair-programming real-world","note":"Alias of Block: data-processing problem, readable code; LLD in Java/Go","round_type":"practical","confidence":"high"}]'::jsonb,'Alias of block. TechPrep Block Process 2025 (techprep.app/blog/block-interview-process), retrieved 2026-06-02; confidence high','2026-06-02'),
('mistralai','Mistral AI','ai','[{"stage":"technical-1","format":"coding + LLM quiz + AI design","note":"Alias of mistral: medium LeetCode + LLM quiz + RAG system design; no dominant type","round_type":"mixed","confidence":"medium"}]'::jsonb,'Alias of mistral. InterviewQuery Mistral AI SWE 2026 (interviewquery.com/prep-guides/mistral-ai-software-engineer), retrieved 2026-06-02; confidence medium','2026-06-02')
ON CONFLICT (company_key) DO UPDATE SET
  display_name  = EXCLUDED.display_name,
  company_type  = EXCLUDED.company_type,
  process_shape = EXCLUDED.process_shape,
  source        = EXCLUDED.source,
  as_of         = EXCLUDED.as_of;

COMMIT;
